### PR TITLE
Add Dots to languages

### PR DESCRIPTION
**Pull request by jaredthecoder**
Adding Dots by @josconno.

### CODE REVIEW

**Comment by angrykoala** [comment]
Please, remove "programming" from the description as is implicit.

**Comment by jaredthecoder** [comment]
Fixed. Let me know if I can change anything else. Thanks!

**Comment by angrykoala** [comment]
The description it's Ok, but it should be under DNA#  language (as it is alphabetical order)

**Comment by jaredthecoder** [comment]
I moved it after DNA#. Let me know if I can change anything else before merging.

**Comment by angrykoala** [comment]
Looks fine, thanks

**Pull request merged**
